### PR TITLE
Added container names, lowered version requirement for docker-compose

### PR DESCRIPTION
**Pull request by ax42**

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
Can you please describe why you think each of these changes is warranted? I want to keep this file as simple as possible for those who aren't docker users, so I want to hear your thoughts on the value add for specifying container names.

...and also what specifically made you choose 2.2 instead of 2.4.

Thanks!

**Comment by LongLiveCHIEF** [comment]
Remember, the docker-compose.yml file included is meant as a template or example.  Just because you had to change the version to work for your specific environment, doesn't mean the template needs to change for every user.

We prefer `2.4`, and for similar reasons, you can add container_names if you want to, but it's a best practice to leave them out of the template.

**Comment by ax42** [comment]
Don't mind the 2.4 vs 2.2.  The `container_name` I consider newbie-friendly (else you end up with container names like `octoPrint_octoprint_1`.

**Comment by LongLiveCHIEF** [comment]
My line of thinking is that the majority of our users (non-docker users) won't even ever see that, and those who know about that, will inherently know enough to add it, if they need the example at all.  So the conclusion I make from there is that I want that file to be as unintimidating as possible, and that means every line counts.

**Pull request closed without merging**
